import { callWithCache, type CacheContext } from '../cache-context.js'
import { OpenRouterClient } from '../../openrouter-client.js'
import {
  STANDARD_PERSONS_SYSTEM_PROMPT,
  STANDARD_PERSONS_USER_PROMPT
} from '../prompts.js'
import { extractJsonArray, repairTruncatedJsonArray } from '../../../../core/markdown.js'
import { slugify, writeUtf8, ensureDir } from '../../../../core/fs-io.js'
import { findExistingPerson, mergePersonInto } from '../dedup/person-dedup.js'
import type { PersonExtraction } from '../../../../core/contracts.js'
import type { OpenRouterUsage } from '../../types.js'
import path from 'node:path'
import { detectLanguageFromText } from '../../../../core/language.js'

export interface StepPersonsParams {
  ctx: CacheContext
  peopleDir: string
  artifactLanguageInstruction?: string
  client: OpenRouterClient
  timeoutMs?: number
}

export interface StepPersonsResult {
  created: string[]
  updated: string[]
  usage: OpenRouterUsage
}

function buildPersonMarkdown(p: PersonExtraction, slug: string, now: string): string {
  const isPt = detectLanguageFromText(p.summary) === 'pt'
  const summaryTitle = isPt ? 'Resumo' : 'Summary'
  const roleTitle = isPt ? 'Papel nos documentos' : 'Role in documents'
  const notesTitle = isPt ? 'Anotações investigativas' : 'Investigative annotations'
  const notesPlaceholder = isPt
    ? '(Preenchido posteriormente pelo agente via :::annotation blocks)'
    : '(Filled later by the agent via :::annotation blocks)'
  const connectionPlaceholder = isPt
    ? '(Auto-gerado pelo renderer via backlinks)'
    : '(Auto-generated by renderer via backlinks)'
  const contextPrefix = isPt ? 'Contexto desta entrada: obra/documento' : 'Context for this entry: source document'
  const pageLabel = isPt ? 'Páginas' : 'Pages'
  const docLabel = isPt ? 'Documento' : 'Document'
  const roleLabel = isPt ? 'Papel' : 'Role'
  const aliasLines = p.aliases.map((a) => `  - "${a}"`).join('\n')
  const tagLines = p.tags.map((t) => `  - ${t}`).join('\n')
  const frontmatter = [
    '---',
    'type: person',
    `name: "${p.name}"`,
    'aliases:',
    aliasLines || '  []',
    `category: ${p.category}`,
    `first_seen_in: "${p.first_seen_in}"`,
    'tags:',
    tagLines || '  []',
    `created: ${now}`,
    `updated: ${now}`,
    '---'
  ].join('\n')

  const roleWithDoc = `${p.role_in_document} (${contextPrefix}: ${p.first_seen_in})`
  const tableRow = `| ${p.first_seen_in} | ${roleWithDoc} | ${p.pages_mentioned.join(', ')} |`
  const contextualSummary = p.summary?.includes(p.first_seen_in)
    ? p.summary
    : `${p.summary}\n\n${contextPrefix} **${p.first_seen_in}**.`

  return [
    frontmatter,
    '',
    `# ${p.name}`,
    '',
    `## ${summaryTitle}`,
    '',
    contextualSummary || `${p.name} — ${roleWithDoc}`,
    '',
    `## ${roleTitle}`,
    '',
    `| ${docLabel} | ${roleLabel} | ${pageLabel} |`,
    '| --- | --- | --- |',
    tableRow,
    '',
    `## ${notesTitle}`,
    '',
    notesPlaceholder,
    '',
    '## Connections',
    '',
    connectionPlaceholder,
    ''
  ].join('\n')
}

/**
 * Etapa 4: extrai Person entities, faz dedup fuzzy e cria/atualiza arquivos em {peopleDir}.
 */
export async function runStepPersons(params: StepPersonsParams): Promise<StepPersonsResult> {
  await ensureDir(params.peopleDir)

  const { content, usage } = await callWithCache(
    params.ctx,
    params.client,
    STANDARD_PERSONS_SYSTEM_PROMPT,
    [STANDARD_PERSONS_USER_PROMPT, params.artifactLanguageInstruction].filter(Boolean).join("\n\n"),
    params.timeoutMs ?? 120_000,
    8192
  )

  let persons: PersonExtraction[] = []
  try {
    persons = JSON.parse(extractJsonArray(content)) as PersonExtraction[]
    if (!Array.isArray(persons)) persons = []
  } catch {
    try {
      persons = JSON.parse(repairTruncatedJsonArray(extractJsonArray(content))) as PersonExtraction[]
      if (!Array.isArray(persons)) persons = []
      console.log(`  [step-persons] JSON reparado: ${persons.length} persons.`)
    } catch {
      console.warn('  [step-persons] Falha ao parsear JSON de persons.')
      persons = []
    }
  }

  const created: string[] = []
  const updated: string[] = []
  const now = new Date().toISOString()

  for (const person of persons) {
    if (!person.name) continue

    const match = await findExistingPerson(person, params.peopleDir)
    if (match) {
      await mergePersonInto(match.filePath, person)
      updated.push(match.filePath)
    } else {
      const slug = slugify(person.name)
      const filePath = path.join(params.peopleDir, `${slug}.md`)
      const markdown = buildPersonMarkdown(person, slug, now)
      await writeUtf8(filePath, markdown)
      created.push(filePath)
    }
  }

  return { created, updated, usage }
}
