import { callWithCache, type CacheContext } from '../cache-context.js'
import { OpenRouterClient } from '../../openrouter-client.js'
import {
  STANDARD_PLACES_SYSTEM_PROMPT,
  STANDARD_PLACES_USER_PROMPT
} from '../prompts.js'
import { extractJsonArray, repairTruncatedJsonArray } from '../../../../core/markdown.js'
import { slugify, writeUtf8, ensureDir } from '../../../../core/fs-io.js'
import { findExistingPlace, mergePlaceInto } from '../dedup/place-dedup.js'
import type { PlaceExtraction } from '../../../../core/contracts.js'
import type { OpenRouterUsage } from '../../types.js'
import path from 'node:path'
import { detectLanguageFromText } from '../../../../core/language.js'

export interface StepPlacesParams {
  ctx: CacheContext
  placesDir: string
  artifactLanguageInstruction?: string
  client: OpenRouterClient
  timeoutMs?: number
}

export interface StepPlacesResult {
  created: string[]
  updated: string[]
  usage: OpenRouterUsage
}

function buildPlaceMarkdown(p: PlaceExtraction, slug: string, now: string): string {
  const isPt = detectLanguageFromText(p.context) === 'pt'
  const summaryTitle = isPt ? 'Resumo' : 'Summary'
  const contextTitle = isPt ? 'Contexto nos documentos' : 'Context in documents'
  const linkedEntitiesTitle = isPt ? 'Entidades vinculadas' : 'Linked entities'
  const linkedEntitiesPlaceholder = isPt ? '(Preenchido pelo agente)' : '(Filled by the agent)'
  const connectionPlaceholder = isPt
    ? '(Auto-gerado pelo renderer via backlinks)'
    : '(Auto-generated by renderer via backlinks)'
  const contextPrefix = isPt ? 'Contexto desta entrada: obra/documento' : 'Context for this entry: source document'
  const pageLabel = isPt ? 'Páginas' : 'Pages'
  const docLabel = isPt ? 'Documento' : 'Document'
  const contextCol = isPt ? 'Contexto' : 'Context'
  const tagLines = p.tags.map((t) => `  - ${t}`).join('\n')
  const contextWithDoc = `${p.context} (${contextPrefix}: ${p.first_seen_in})`
  const tableRow = `| ${p.first_seen_in} | ${contextWithDoc} | ${p.pages_mentioned.join(', ')} |`
  const contextualSummary = p.context?.includes(p.first_seen_in)
    ? p.context
    : `${p.context}\n\n${contextPrefix} **${p.first_seen_in}**.`

  const frontmatter = [
    '---',
    'type: place',
    `name: "${p.name}"`,
    `country: "${p.country}"`,
    `city: "${p.city}"`,
    `neighborhood: "${p.neighborhood ?? ''}"`,
    `address: "${p.address ?? ''}"`,
    'coordinates: null',
    `first_seen_in: "${p.first_seen_in}"`,
    'tags:',
    tagLines || '  []',
    `created: ${now}`,
    `updated: ${now}`,
    '---'
  ].join('\n')

  return [
    frontmatter,
    '',
    `# ${p.name}`,
    '',
    `## ${summaryTitle}`,
    '',
    contextualSummary || `${p.name}, ${p.city}`,
    '',
    `## ${contextTitle}`,
    '',
    `| ${docLabel} | ${contextCol} | ${pageLabel} |`,
    '| --- | --- | --- |',
    tableRow,
    '',
    `## ${linkedEntitiesTitle}`,
    '',
    linkedEntitiesPlaceholder,
    '',
    '## Connections',
    '',
    connectionPlaceholder,
    ''
  ].join('\n')
}

/**
 * Etapa 6: extrai Place entities, faz dedup e cria/atualiza arquivos.
 * Estrutura: {placesDir}/{country}/{city}/{slug}.md
 */
export async function runStepPlaces(params: StepPlacesParams): Promise<StepPlacesResult> {
  await ensureDir(params.placesDir)

  const { content, usage } = await callWithCache(
    params.ctx,
    params.client,
    STANDARD_PLACES_SYSTEM_PROMPT,
    [STANDARD_PLACES_USER_PROMPT, params.artifactLanguageInstruction].filter(Boolean).join("\n\n"),
    params.timeoutMs ?? 120_000,
    8192
  )

  let places: PlaceExtraction[] = []
  try {
    places = JSON.parse(extractJsonArray(content)) as PlaceExtraction[]
    if (!Array.isArray(places)) places = []
  } catch {
    try {
      places = JSON.parse(repairTruncatedJsonArray(extractJsonArray(content))) as PlaceExtraction[]
      if (!Array.isArray(places)) places = []
      console.log(`  [step-places] JSON reparado: ${places.length} places.`)
    } catch {
      console.warn('  [step-places] Falha ao parsear JSON de places.')
      places = []
    }
  }

  const created: string[] = []
  const updated: string[] = []
  const now = new Date().toISOString()

  for (const place of places) {
    if (!place.name) continue

    const match = await findExistingPlace(place, params.placesDir)
    if (match) {
      await mergePlaceInto(match.filePath, place)
      updated.push(match.filePath)
    } else {
      const country = place.country || 'Unknown'
      const city = place.city || 'Unknown'
      const placeDir = path.join(params.placesDir, country, city)
      await ensureDir(placeDir)

      const slug = slugify(place.name)
      const filePath = path.join(placeDir, `${slug}.md`)
      const markdown = buildPlaceMarkdown(place, slug, now)
      await writeUtf8(filePath, markdown)
      created.push(filePath)
    }
  }

  return { created, updated, usage }
}
